int learn5() //strings
{
    printf("\n**********  STRING  **********                       \n");
    printf("\n•String is an array of character or a pointer to a portion of memory containing ASCII character\n ");
    printf("\n•String can also be defined as sequence of zero or more character followed by a NULL '\0'character. ");
    printf("\n•character type of value are enclosed in single quotes.\n\n     •string type values are enclosed by double quotes.\nexample: \"a\" is a string value\n");
    printf("\nDeclaring a variable\n");
    printf("syntax: char string_name[string_size]\nwhere ,\n     •char is a data type of string.\n     •string_name is name for string variable.\n     •string_size is length of string which is to be stored.\n    ->string_size is the length of string i.e no. of characters stored in the string (excluding NULL character)\n ");
    printf("example: char name[21];\n->here 20 character are stored by character and 1 space is filled by the NULL making the end of the string\n");
    printf("string initialization of string :\nchar name [11]={'p','r','a','k','h','y','a','t','h','\0'};\n");
    printf("char name[11]=\"prakayath\";\n");
    printf("     •Both are same, if we specify characters separately we should'' for each character and finally enclosing all the character within the braces {} and if we directly specify the entire string at one time we use ""\n ");
    printf("\nIn the above example: \nchar name[11]={'p','r','a','k','h','y','a','t','h','\0'};\n name[0] holds 'p' name[1] holds 'r' name[2] hods 'a'so on name[9] holds the '\0'\n remaining memory is wasted.\n");
    printf("consider the example :\n char name[11]=\"prakhayath\"\n");
    printf("Here string is initialized as a unit, and null character supplied by the compiler automatically. \n");
    printf("The values is stored in these two strings as identical.\n");
    printf("\nString input/output functions :\n");
    printf("\n                                    string i/o functions                            \n");
    printf("        _______________________________________|______________________________________\n");
    printf("        |                                                                            |\n");
    printf("    formated                                                                     un-formated\n");
    printf("        |                                                                            |\n");
    printf("        |-->printf -for output                                                       |-->puts-for output\n");
    printf("        |-->scanf -for input                                                         |-->gets-for input\n");
    printf("\n\n/* program to illustrate formated I/O for strings */\n");
    printf("\n#include<stdio.h>\nvoid main()\n{\n char name[20];\n printf(\"enter Name :\");\n scanf(\"%%s\",name);\n printf(\"your name is %%s\",name);\n}\n");
    printf("output :\nenter name: prakhayath\nyourname is prakhayath.\n");
    printf("\n\n/* program to illustrate un-formated I/O for strings */\n");
    printf("\n#include<stdio.h>\nvoid main()\n{\n char name[20];\n printf(\"enter Name :\");\n gets(name);\n printf(\"your name is :\");\n puts(name)\n}\n");
    printf("output :\nenter name: prakhayath\nyourname is prakhayath.\n");
    printf("\n\narray of strings /multidimensional strings :\n");
    printf("     •The two dimensional character array which consist of strings as its individual elements,is said to be an array of string \nsyntax:\n  char string_name[size_of_rows][size_of_cols];\n ");
    printf("example:char names[3][10];\n initialization:\nchar day[7][10]={\"sunday\",\"monday\",\"tuesday\",\"wednesday\",\"thursday\",\"friday\"}\n");
    printf("\n   0   1   2   3   4   5   6   7   8   9   ");
    printf("\n ________________________________________\n");
    printf("0| s | u | n | d | a | y |\\0 |   |   |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("1| m | o | n | d | a | y |\\0 |   |   |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("2| t | u | e | s | d | a | y |\\0 |   |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("3| w | e | d | n | e | s | d | a | y |\\0 |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("4| t | h | u | r | s | d | a | y |\\0 |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("5| f | r | i | d | a | y |\\0 |   |   |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("6| s | a | t | u | r | d | a | y |\\0 |   |\n");
    printf(" |___|___|___|___|___|___|___|___|___|___|\n");
    printf("\n memory is created for the above initialization as illustrated\n");
    printf("     •The above initialization creates 7 rows and 10 columns using which different strings are stored in day array as shown \n");
    printf("     •Last character of each string is always NULL character '\0'\n");
    printf("     • day[0] contains first i.e \"sunday\"\n");
    printf("       day[1] contains second i.e \"monday\"\n");
    printf("                    .                       \n");
    printf("                    .                       \n");
    printf("                    .                       \n");
    printf("       day[6] contains second i.e \"saturday\"\n");
    printf("\n\nString Manipulation function:\n");
    printf("1.strlen():to find the length of the string\n2.strcpy():is the copy string with another\n3.strncpy():copy the string up to an length\n4.strcmp():compare of two strings case sensitive\n5.stricmp():compare of tow strings not case sensitive\n");
    printf("6.strcmp():compare the two string upto the lengths\n7.strincmp():compare of two strings up to their length not case sensitive\n8.strlwr():it convert upper case character into lower case\n9.strupr()it convert lowercase letter into uppercase\n");
    printf("10.strcat():this will combine two strings to make one sentence\n11.strrev():reversing the string the string\n12.strset():replacing the characters by symbols\n13.strnset():replacing the character by symbols upto length specified\n");
    printf("\n\n  This is a brif representation of string. \n");
}
